### ISSUE TITLE
log file location

### ISSUE THREAD

**Issue by monkeydri** [root-gg/plik#254]
I feel silly to open an issue for that but I cannot find plik log file.

I am using plik docker image and looked at usual /var/log location and ~/server dir but could not find any log file there.

I would like to see the root of the error 500 I have on save (Oops ! (500) Unable to save file).

**Comment by MAGICCC** [comment]
Since it's docker you can use docker-compose logs -f to get a live log output

**Comment by monkeydri** [comment]
Thanks a lot ! As I believed it is a permission problem for the upload directory (a docker volume is mounted at /home/plik/server/files  but this is another issue.

**Comment by camathieu** [comment]
In docker Plik runs with uid:gid 1000:1000.
You'll need to configure your mounted volume accordingly.

**Comment by LivingWithHippos** [comment]
Thanks it worked. I think plik should automatically set them like the other containers. For future reference this is my `docker-compose.yml`

```yaml
version: '3'
services:
  app:
    container_name: plik
    image: rootgg/plik:latest
    volumes:
      - ./files:/home/plik/server/files
      - ./config/plikd.cfg:/home/plik/server/plikd.cfg
    restart: unless-stopped
```

and this is the command I ran on my folder to fix the error

`sudo chown 1000:1000 .files/`

The original error in the docker logs was 

`[11/03/2020 13:36:04][WARNING ][[92.246.120.111][9vwqwUWs13iI4EFl][gvsofkyw51.jpg]] internal server error -- unable to create upload directory -- 500`
