### ISSUE TITLE
Docker broken

### ISSUE THREAD

**Issue by NoxInmortus** [root-gg/plik#326]
Hello,

Latest docker image seems broken for amd64 at least.

Logs shows only
```
/bin/sh: ./plikd: not found
```

**Comment by camathieu** [comment]
Hi, it looks fine from here could you give more details about your setup ?

```
🪂 ➜  plik git:(master) ✗ docker pull rootgg/plik
Using default tag: latest
latest: Pulling from rootgg/plik
cbdbe7a5bc2a: Pull complete 
bacff73ffef3: Pull complete 
187384fc66b0: Pull complete 
bd63e56b6912: Pull complete 
ea3a40302078: Pull complete 
5e54b61bad2a: Pull complete 
3af2ef16215d: Pull complete 
41791abcc4c6: Pull complete 
Digest: sha256:fc2d9252bed7d5946be717e69e7e6e93bd5ab80780b199bc58e6a95c776a4a87
Status: Downloaded newer image for rootgg/plik:latest
docker.io/rootgg/plik:latest
🪂 ➜  plik git:(master) ✗ docker run rootgg/plik
[10/01/2020 18:26:50][INFO    ] Starting plikd server v1.3
[10/01/2020 18:26:50][INFO    ] Starting server at http://0.0.0.0:8080
[10/01/2020 18:26:50][INFO    ] Will clean old uploads in 10673 seconds.
```

Are you upgrading ?

**Comment by NoxInmortus** [comment]
@camathieu Hello back,

Yes the container image have been updated from the previous one. Auto-update is done monthly.

This is my configuation
```

# https://github.com/root-gg/plik
  - name: plik
    image: rootgg/plik
    restart_policy: unless-stopped
    security_opts:
      - no-new-privileges:true
    volumes:
      - plik-data:/home/plik/server/files
      - plik-conf:/home/plik/server
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8001:8080
    log_options:
      max-size: '10m'
      max-file: '1'
```
