### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by pieterhouwen** [root-gg/plik#350]
When using Plik on port 443 it would be best if traffic from port 80 is automatically redirected to 443 instead of just refusing to connect.

**Comment by unbelauscht** [comment]
You could run nginx or traefik as reverse proxy to expose Plik publicly and configure any of both to redirect traffic.

**Comment by pieterhouwen** [comment]
While certainly possible using nginx gave me alot of headache when trying to make it work (gave up eventually) so I'd much rather have the redirect :)

**Comment by camathieu** [comment]
In fact when running on HTTPS/443 we have no HTTP server running on 80
available to serve the redirect. A reverse proxy like Apache or Nginx is
the way to go.

**Comment by michaelcrunch** [comment]
I hope this helps with the `nginx` redirect issues @pieterhouwen 
`/etc/nginx/conf.d/plik-http.conf`
```
server_tokens off;

server {
    listen 80;
    server_name [YOUR DOMAIN NAME];

    location / {
        rewrite ^ https://[YOUR DOMAIN NAME]$request_uri? permanent;
    }
}
```
`/etc/nginx/conf.d/plik-https.conf`
```
server_tokens off;

upstream plik {
  server localhost:8080;
  keepalive 300;
}

server {
  proxy_max_temp_file_size 0; 
  client_max_body_size 10000M; 
  listen  443 ssl;

  access_log  /var/log/nginx/[YOUR DOMAIN NAME]/access.log;
  error_log /var/log/nginx/[YOUR DOMAIN NAME]/error.log warn;

  ssl_certificate         /path/to/your/certificates/fullchain.pem;
  ssl_certificate_key     /path/to/your/certificates/privkey.pem;
  ssl_trusted_certificate /path/to/your/certificates/fullchain.pem;
  ssl_protocols TLSv1.2;
  ssl_ciphers HIGH:!aNULL:!MD5;


  location / {
    allow all;
    proxy_pass          http://plik;
    proxy_http_version  1.1;
    proxy_set_header  Upgrade $http_upgrade;
    proxy_set_header  Connection "upgrade";
  }
}
```

**Comment by unbelauscht** [comment]
If you want to run it on Docker with `traefik:v2.4.8` as reverse proxy, here is a part of my `docker-compose.yml` showing traefik configuration:

```
version: '3.7'
services:
        web:
                image: rootgg/plik:1.2.4
                        labels:
                                - "traefik.enable=true"
                                - "traefik.http.services.plik.loadbalancer.server.port=8080"
                                - "traefik.http.routers.plik.entrypoints=web-secure"
                                - "traefik.http.routers.plik.rule=Host(`plik.example.net`)"
                                - "traefik.http.routers.plik.tls=true"
                                - "traefik.http.routers.plik.tls.certresolver=letsencrypt"
                                - "traefik.http.routers.plik.middlewares=plik@docker"
                                - "traefik.http.middlewares.plik.headers.framedeny=true"
                                - "traefik.http.middlewares.plik.headers.contentTypeNosniff=true"
                                - "traefik.http.middlewares.plik.headers.referrerPolicy=same-origin"
                                - "traefik.http.middlewares.plik.headers.accesscontrolallowmethods=GET,POST"
                                - "traefik.http.middlewares.plik.headers.forcestsheader=true"
                                - "traefik.http.middlewares.plik.headers.STSIncludeSubdomains=true"
                                - "traefik.http.middlewares.plik.headers.STSPreload=true"
                                - "traefik.http.middlewares.plik.headers.stsSeconds=31536000"
                                - "traefik.http.middlewares.plik.headers.browserXssFilter=true"
                                - "traefik.http.middlewares.plik.headers.browserxssfilter=1"
```
