### ISSUE TITLE
Docker export/persist database

### ISSUE THREAD

**Issue by danielbeicht** [root-gg/plik#361]
Hi,

I currently try to make the Sqlite database persistent using docker. Unfortunately the documentation only explains how to mount the files-folder and config-file. So far I had no luck mounting the plik.db-file from the server-folder.
Does anyone know how to persistently store the database on the host?

Thanks in advance.

**Comment by paulkitt** [comment]
We do it like this and works great so far.
```
version: '3'                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                              
services:                                                                                                                                                                                                                                     
  plik:                                                                                                                                                                                                                                       
    image: rootgg/plik:latest                                                                                                                                                                                                                 
    container_name: plik                                                                                                                                                                                                                      
    restart: always                                                                                                                                                                                                                           
    ports:                                                                                                                                                                                                                                    
      - '127.0.0.1:9999:9999'                                                                                                                                                                                                                 
    volumes:                                                                                                                                                                                                                                  
      - /srv/plik/metadata:/home/plik/server/metadata                                                                                                                                                                                         
      - /srv/plik/files:/home/plik/server/files                                                                                                                                                                                               
      - ./plikd.cfg:/home/plik/server/plikd.cfg                                                                                                                                                                                               
      - ./background.jpg:/home/plik/webapp/dist/img/background.jpg:ro           
```
