### ISSUE TITLE
Streaming function uploads to server immediately.

### ISSUE THREAD

**Issue by bleomycin** [root-gg/plik#449]
Streaming function uploads to server immediately.  Tested with Microsoft Edge and Google Chrome on windows 11. Toggle the streaming option, select file to upload, click upload button to generate link and the file begins uploading to the server immediately. Streaming function does not seem to work? Please let me know if there is anything else I can do to help debug.

Plik Version : 1.3.6
go1.18.2 linux/amd64

docker-compose.yml

```
version: "2"
services:
  plik:
    image: rootgg/plik:latest
    container_name: plik
    volumes:
      - /opt/docker/plik/config/plikd.cfg:/home/plik/server/plikd.cfg
      - /opt/docker/plik/config/data:/data
    ports:
      - 8081:8080   
    restart: "unless-stopped"
```

```
[06/28/2022 21:28:13][INFO    ][[192.168.208.1][3kOh7W38hO2sVT2n]] POST /upload [200 OK] (858.312µs)
[06/28/2022 21:28:13][INFO    ][[192.168.208.1]] GET /qrcode?url=https%3A%2F%2Fsend.mydomain.com%2F%23%2F%3Fid%3D3kOh7W38hO2sVT2n&size=200 [200 OK] (9.097863ms)
```
