### ISSUE TITLE
Plik in Docker can't see actual client IP

### ISSUE THREAD

**Issue by jmbluethner** [root-gg/plik#530]
Hello everyone :)

Currently working on my first steps with Plik.  
However, I'm facing an issue.

I'm running Plik as a Docker container.  
Here's my `docker-compose.yml`:  

```yaml
services:
  plik:
    image: rootgg/plik:latest
    container_name: plik
    volumes:
      - /home/xxx/docker/plik/plikd.cfg:/home/plik/server/plikd.cfg
      - /home/xxx/docker/plik/data:/data
    ports:
      - 3050:8080
    restart: "unless-stopped"
```

When I look into the log via `docker logs plik -f` I can see that the incoming upload request is being sent from `172.18.0.1`.  
```
[05/02/2025 00:09:02][INFO    ][[172.18.0.1][photo_5224367892546581015_y.jpg]] POST / [200 OK] (8.909174ms)
```

But I'm uploading from a remote machine. So what I'd expect is my global IPv4. `172.18.0.1` is the Docker networks gateway. Plik is using `172.18.0.2`.  

The problem arising from all this is, that the `UploadWhitelist` inside of `plikd.cfg` becomes useless since the Plik container appears to be only seeing `172.18.0.1`.

Now I'm wondering - Is there a fix for this?  
I guess adding `network_mode: "host"` to my `docker-compose.yml` might be a way?
